### PR TITLE
adjust mypy checks to support Python 3.8+ in Debian

### PR DESCRIPTION
**Pull request by mr-c**
Testing against Python 3.5 (which is end of life) is causing the Debian autopkg tests to fail with the latest version of mypy (0.910)

https://ci.debian.net/data/autopkgtest/testing/amd64/t/typedload/15404161/log.gz

### CODE REVIEW

**Comment by ltworf** [comment]
Eh I understand, but I can't just drop support for a python version that maybe people with pip use.

Oddly, I just added type ignore and that passes locally but fails on the gh CI, even though seemingly the py and mypy version used are the same.

I will do some more attempts later.

**Comment by mr-c** [comment]
> Eh I understand, but I can't just drop support for a python version that maybe people with pip use.

Oh, you don't have to drop support for it. Just don't hardcode it in `mypy.ini`.

https://mypy.readthedocs.io/en/stable/config_file.html#confval-python_version

For example, in my projects we run `mypy` (without any `python_version` in `mypy.ini`) via Tox once each for every version of Python we support: https://github.com/common-workflow-language/schema_salad/blob/3aa5aa153a00d8042e495c494ea1fd86cf572bfb/tox.ini#L29

Here is how we call `tox` from GitHub Actions: https://github.com/common-workflow-language/schema_salad/blob/3aa5aa153a00d8042e495c494ea1fd86cf572bfb/.github/workflows/ci-tests.yml#L11

I can amend this PR to implement this approach, if you'd like.

My goal is a new release of `typedload` in Debian unstable to unblock the latest `mypy` release :-)

https://qa.debian.org/excuses.php?package=mypy

**Comment by mr-c** [comment]
In case you run into this: starting with mypy 0.900 they no longer ship third party stubs in the mypy typeshed, and this includes the backport of `dataclasses` for Python 3.5: http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html The type hints for `dataclasses` are now published in a new package: https://pypi.org/project/types-dataclasses/

This is what triggered the autopkgtest failure with typedload, which is a bit funny for Debian as the older version of Python in Debian's Bullseye and newer is Python 3.9 :-)

**Comment by ltworf** [comment]
I tried to run mypy with each py version rather than just once, but every python version has different ideas of which ignores are needed, so it fails.

I also tried putting the import behind a try statement but mypy complains anyway (which seems a thing I could open a ticket about).

With this pr basically I'd lose syntax checking done by mypy and rely purely on the tests running on python3.5 and 3.6 to make sure it still works.

Any other ideas?

**Comment by ltworf** [comment]
I mean, I can always make it less strict and move on

**Comment by mr-c** [comment]
@ltworf I've re-done this PR so that Debian can test with Python 3.8+ and your CI can test with your existing setup

**Comment by ltworf** [comment]
Hello,

thanks for the help. In the end I went for a different approach that doesn't require creating a patch, at the cost of telling mypy to not error out for "superfluous" ignores.

So I'm closing this and I will make a new release and upload to unstable.

**Comment by mr-c** [comment]
Thanks! Yeah, whatever solution works for you is good for me.

**Pull request closed without merging**
